# Generated by Django 6.0.2 on 2026-03-23 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='created',
            new_name='created_at',
        ),
    ]
