# Generated by Django 6.0.2 on 2026-03-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_created_person_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='created_at',
            new_name='created',
        ),
    ]
